apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-example-config
  labels:
    app.kubernetes.io/name: vault-example
data:
  extraconfig-from-values.hcl: |-
    disable_mlock = true
    ui = true
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_cert_file = "/vault/ssl/vault-example.pem"
      tls_key_file = "/vault/ssl/vault-example-key.pem"
      tls_min_version = "tls12"
      cluster_address = "[::]:8201"
    }
    storage "file" {
      path = "/vault/data"
    }
